spring.application.name=spendwise
spring.datasource.url=jdbc:mysql://localhost:3306/spendwise
spring.datasource.username=root
spring.datasource.password=Shreya@24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
